import React, { useMemo, useState } from 'react';
const TOOL_ID='js-minifier';
const privacy='Your data stays in your browser. Nothing is uploaded.';
const sample='// demo\nfunction hello(name) {\n  console.log("Hello " + name);\n}';
function basicMinifyJs(code){ let out='', quote=null, esc=false, line=false, block=false; for(let i=0;i<code.length;i++){ const c=code[i], n=code[i+1]; if(line){ if(c==='\n'){line=false; out+=' ';} continue;} if(block){ if(c==='*'&&n==='/'){block=false;i++;} continue;} if(quote){ out+=c; if(esc){esc=false;} else if(c==='\\'){esc=true;} else if(c===quote){quote=null;} continue;} if((c==='"'||c==="'"||c==='`')){quote=c; out+=c; continue;} if(c==='/'&&n==='/'){line=true;i++;continue;} if(c==='/'&&n==='*'){block=true;i++;continue;} out+=c;} return out.replace(/\s+/g,' ').replace(/\s*([{}();,:=+\-*/<>])\s*/g,'$1').trim(); }
const copy=t=>navigator.clipboard?.writeText(t);
function download(name,text){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:'text/javascript'})); a.download=name; a.click(); }
function JsMinifier(){ const [input,setInput]=useState(sample); const output=useMemo(()=>basicMinifyJs(input),[input]); const pct=input.length?Math.max(0,(1-output.length/input.length)*100):0; return <div className="tool-card phase1b-tool dev-tool" data-tool={TOOL_ID}><div className="tool-status-line"><span className="status-ready">Working client-side</span><span>{privacy}</span></div><h2>JS Minifier</h2><p className="info-note">Basic minifier: comments aur safe whitespace remove karta hai. Full parser/optimizer nahi hai.</p><div className="phase1b-two-panel"><label>JS input<textarea className="form-textarea code-area" value={input} onChange={e=>setInput(e.target.value)} /></label><label>Minified output<textarea className="form-textarea code-area" readOnly value={output} /></label></div><div className="result-card-grid"><div><span>Before</span><strong>{input.length} chars</strong></div><div><span>After</span><strong>{output.length} chars</strong></div><div><span>Reduction</span><strong>{pct.toFixed(1)}%</strong></div></div><div className="tool-button-row"><button className="btn btn-secondary" onClick={()=>copy(output)} disabled={!output}>Copy</button><button className="btn btn-secondary" onClick={()=>download('minified.js',output)} disabled={!output}>Download .js</button></div></div>; }
export default JsMinifier;
