import React, { useMemo, useState } from 'react';
const TOOL_ID='lorem-ipsum';
const privacy='Your data stays in your browser. Nothing is uploaded.';
const words='lorem ipsum dolor sit amet consectetur adipiscing elit sed do eiusmod tempor incididunt ut labore et dolore magna aliqua'.split(' ');
const copy=t=>navigator.clipboard?.writeText(t);
function download(name,text){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type:'text/plain'})); a.download=name; a.click(); }
function makeSentence(i,len=12){ const arr=[]; for(let n=0;n<len;n++) arr.push(words[(i+n)%words.length]); const s=arr.join(' '); return s.charAt(0).toUpperCase()+s.slice(1)+'.'; }
function LoremIpsum(){ const [mode,setMode]=useState('paragraphs'); const [count,setCount]=useState(3); const output=useMemo(()=>{ const c=Math.max(1,Math.min(100,Number(count)||1)); if(mode==='words') return Array.from({length:c},(_,i)=>words[i%words.length]).join(' '); if(mode==='sentences') return Array.from({length:c},(_,i)=>makeSentence(i*3)).join(' '); return Array.from({length:c},(_,p)=>Array.from({length:4},(_,i)=>makeSentence(p*7+i*4)).join(' ')).join('\n\n'); },[mode,count]); return <div className="tool-card phase1b-tool dev-tool" data-tool={TOOL_ID}><div className="tool-status-line"><span className="status-ready">Working client-side</span><span>{privacy}</span></div><h2>Lorem Ipsum Generator</h2><div className="simple-form-grid"><label>Type<select className="form-select" value={mode} onChange={e=>setMode(e.target.value)}><option value="words">Words</option><option value="sentences">Sentences</option><option value="paragraphs">Paragraphs</option></select></label><label>Count<input className="form-input" type="number" min="1" max="100" value={count} onChange={e=>setCount(e.target.value)} /></label></div><textarea className="form-textarea code-area" readOnly value={output}/><div className="tool-button-row"><button className="btn btn-secondary" onClick={()=>copy(output)}>Copy</button><button className="btn btn-secondary" onClick={()=>download('lorem-ipsum.txt',output)}>Download .txt</button></div></div>; }
export default LoremIpsum;
