import React, { useMemo, useState } from 'react';
const TOOL_ID='password-generator';
const privacy='Your data stays in your browser. Nothing is uploaded.';
const sets={upper:'ABCDEFGHJKLMNPQRSTUVWXYZ',lower:'abcdefghijkmnopqrstuvwxyz',numbers:'23456789',symbols:'!@#$%^&*()-_=+[]{};:,.?'};
const similar=/[Il1O0]/g;
function pick(s){ return s[Math.floor(Math.random()*s.length)]; }
const copy=t=>navigator.clipboard?.writeText(t);
function PasswordGenerator(){ const [length,setLength]=useState(16); const [opts,setOpts]=useState({upper:true,lower:true,numbers:true,symbols:true,exclude:true}); const [password,setPassword]=useState(''); const charset=useMemo(()=>Object.entries(sets).filter(([k])=>opts[k]).map(([,v])=>opts.exclude?v.replace(similar,''):v).join(''),[opts]); const strength=useMemo(()=>{ const count=['upper','lower','numbers','symbols'].filter(k=>opts[k]).length; const score=Number(length)+count*5; return score>=32?'Strong':score>=20?'Medium':'Weak';},[length,opts]); const generate=()=>{ if(!charset) {setPassword('Select at least one character set.');return;} let out=''; for(let i=0;i<Number(length);i++) out+=pick(charset); setPassword(out);}; const toggle=k=>setOpts(o=>({...o,[k]:!o[k]})); return <div className="tool-card phase1b-tool dev-tool" data-tool={TOOL_ID}><div className="tool-status-line"><span className="status-ready">Working client-side</span><span>{privacy}</span></div><h2>Password Generator</h2><div className="simple-form-grid"><label>Length<input className="form-input" type="number" min="6" max="128" value={length} onChange={e=>setLength(e.target.value)} /></label></div><div className="phase1b-checks">{['upper','lower','numbers','symbols'].map(k=><label key={k}><input type="checkbox" checked={opts[k]} onChange={()=>toggle(k)} /> {k}</label>)}<label><input type="checkbox" checked={opts.exclude} onChange={()=>toggle('exclude')} /> exclude similar</label></div><div className="tool-button-row"><button className="btn btn-primary" onClick={generate}>Generate password</button><button className="btn btn-secondary" onClick={()=>copy(password)} disabled={!password}>Copy</button></div><div className="result-panel"><strong>{password}</strong><p>Strength: {strength}</p></div></div>; }
export default PasswordGenerator;
