import React, { useMemo, useState } from 'react';
import QRCode from 'qrcode';
import DownloadButton from '../../components/DownloadButton';
import ErrorMessage from '../../components/ErrorMessage';
import LoadingSpinner from '../../components/LoadingSpinner';
const TOOL_ID='vcard-qr-generator';
const privacy='Your data stays in your browser. Nothing is uploaded.';
const esc=v=>(v||'').replace(/\n/g,'\\n');
const copy=t=>navigator.clipboard?.writeText(t);
function downloadText(name,text,type='text/plain'){ const a=document.createElement('a'); a.href=URL.createObjectURL(new Blob([text],{type})); a.download=name; a.click(); }
function VCardQrGenerator(){ const [fullName,setFullName]=useState(''); const [phone,setPhone]=useState(''); const [email,setEmail]=useState(''); const [company,setCompany]=useState(''); const [title,setTitle]=useState(''); const [website,setWebsite]=useState(''); const [address,setAddress]=useState(''); const [qr,setQr]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const vcard=useMemo(()=>`BEGIN:VCARD\nVERSION:3.0\nFN:${esc(fullName)}\nORG:${esc(company)}\nTITLE:${esc(title)}\nTEL:${esc(phone)}\nEMAIL:${esc(email)}\nURL:${esc(website)}\nADR:;;${esc(address)};;;;\nEND:VCARD`,[fullName,phone,email,company,title,website,address]); const generate=async()=>{setError('');setQr(''); if(!fullName.trim()) {setError('Full name required hai.');return;} try{setLoading(true);setQr(await QRCode.toDataURL(vcard,{width:512,margin:2,errorCorrectionLevel:'M'}));}catch{setError('vCard QR generate nahi ho saka.');}finally{setLoading(false);}}; return <div className="tool-card phase1b-tool qr-tool" data-tool={TOOL_ID}><div className="tool-status-line"><span className="status-ready">Working client-side</span><span>{privacy}</span></div><h2>vCard QR Generator</h2><div className="simple-form-grid"><label>Full name<input className="form-input" value={fullName} onChange={e=>setFullName(e.target.value)} /></label><label>Phone<input className="form-input" value={phone} onChange={e=>setPhone(e.target.value)} /></label><label>Email<input className="form-input" value={email} onChange={e=>setEmail(e.target.value)} /></label><label>Company<input className="form-input" value={company} onChange={e=>setCompany(e.target.value)} /></label><label>Job title<input className="form-input" value={title} onChange={e=>setTitle(e.target.value)} /></label><label>Website<input className="form-input" value={website} onChange={e=>setWebsite(e.target.value)} /></label></div><label className="field-stack"><span className="field-title">Address</span><textarea className="form-textarea" value={address} onChange={e=>setAddress(e.target.value)} /></label><textarea className="form-textarea code-area" readOnly value={vcard}/><div className="tool-button-row"><button className="btn btn-primary" onClick={generate}>Generate QR</button><button className="btn btn-secondary" onClick={()=>copy(vcard)}>Copy vCard</button><button className="btn btn-secondary" onClick={()=>downloadText('contact.vcf',vcard,'text/vcard')}>Download .vcf</button></div><ErrorMessage message={error}/>{loading&&<LoadingSpinner label="Generating vCard QR..."/>}{qr&&<div className="result-panel centered-result"><img className="qr-preview" src={qr} alt="vCard QR"/><DownloadButton href={qr} filename="vcard-qr-generator.png">Download QR PNG</DownloadButton></div>}</div>; }
export default VCardQrGenerator;
