import React, { useMemo, useState } from 'react';
import QRCode from 'qrcode';
import DownloadButton from '../../components/DownloadButton';
import ErrorMessage from '../../components/ErrorMessage';
import LoadingSpinner from '../../components/LoadingSpinner';
const TOOL_ID='whatsapp-qr-generator';
const privacy='Your data stays in your browser. Nothing is uploaded.';
const copy=(text)=>navigator.clipboard?.writeText(text);
function WhatsAppQrGenerator(){ const [country,setCountry]=useState('92'); const [phone,setPhone]=useState(''); const [message,setMessage]=useState(''); const [size,setSize]=useState(512); const [qr,setQr]=useState(''); const [error,setError]=useState(''); const [loading,setLoading]=useState(false); const number=useMemo(()=>`${country}${phone}`.replace(/\D/g,''),[country,phone]); const link=useMemo(()=>`https://wa.me/${number}${message?`?text=${encodeURIComponent(message)}`:''}`,[number,message]); const generate=async()=>{setError('');setQr(''); if(!number){setError('Country code aur phone number required hain.');return;} try{setLoading(true);setQr(await QRCode.toDataURL(link,{width:Number(size),margin:2,errorCorrectionLevel:'M'}));}catch{setError('WhatsApp QR generate nahi ho saka.');}finally{setLoading(false);}}; return <div className="tool-card phase1b-tool qr-tool" data-tool={TOOL_ID}><div className="tool-status-line"><span className="status-ready">Working client-side</span><span>{privacy}</span></div><h2>WhatsApp QR Generator</h2><p className="info-note">QR link chat open karta hai; message auto-send claim nahi karta.</p><div className="simple-form-grid"><label>Country code<input className="form-input" value={country} onChange={e=>setCountry(e.target.value)} /></label><label>Phone number<input className="form-input" value={phone} onChange={e=>setPhone(e.target.value)} /></label><label>QR size<select className="form-select" value={size} onChange={e=>setSize(e.target.value)}><option value="256">256</option><option value="512">512</option><option value="768">768</option></select></label></div><label className="field-stack"><span className="field-title">Optional message</span><textarea className="form-textarea" value={message} onChange={e=>setMessage(e.target.value)} /></label><textarea className="form-textarea code-area" readOnly value={link}/><div className="tool-button-row"><button className="btn btn-primary" onClick={generate}>Generate QR</button><button className="btn btn-secondary" onClick={()=>copy(link)}>Copy link</button></div><ErrorMessage message={error}/>{loading&&<LoadingSpinner label="Generating WhatsApp QR..."/>}{qr&&<div className="result-panel centered-result"><img className="qr-preview" src={qr} alt="WhatsApp QR"/><DownloadButton href={qr} filename="whatsapp-qr-generator.png">Download PNG</DownloadButton></div>}</div>; }
export default WhatsAppQrGenerator;
